### ISSUE TITLE
Phantom points run from point n to point n+3 (not n+1 to n+4)

### ISSUE THREAD

**Issue by Lorp** [TypeNetwork/Parama-roundup#17]
In README.md it looks like the 4 phantom points are incorrectly defined. From the spec:
> If the entire set of contours for a glyph requires “n” points (i.e., contour points numbered from 0 to n-1), then the scaler will add points n, n+1, n+2, and n+3.

So replace this:

* n+1 = (origin, origin)
* n+2 = (advance width, origin)
* n+3 = (origin, ascender)
* n+4 = (origin, descender)

… with this:

* n = (origin, origin)
* n+1 = (advance width, origin)
* n+2 = (origin, ascender)
* n+3 = (origin, descender)

**Comment by djrrb** [comment]
Thank you for catching my mistake! It is corrected. 🙌
